### ISSUE TITLE
Bluemix crashing on start - "string contains null byte (ArgumentError)"

### ISSUE THREAD

**Issue by stoprocent** [cloudfoundry/ruby-buildpack#103]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

**cf version 6.34.1+bbdf81482.2018-01-17**

What version of the buildpack you are using?

**Ruby Sinatra**

If you were attempting to accomplish a task, what was it you were attempting to do?

**Restart a Bluemix app instance**

What did you expect to happen?

**Bluemix app instance to start**

What was the actual behavior?

**Bluemix app instance crashed**

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

---

Hi Guys

I have a problem after I did restart my Ruby Sinatra instance on Bluemix.
This is the log output. It looks like there is a problem with one of the dependencies.

``` Bash
2018-05-28T10:19:03.77+0200 [API/2] OUT Updated app with guid 979f7403-b13c-4e85-936b-744064b691bc ({"name"=>"vRIOT Kontakt Dashboard", "instances"=>1, "memory"=>256, "disk_quota"=>1024, "environment_json"=>"PRIVATE DATA HIDDEN"})
2018-05-28T10:19:12.27+0200 [API/5] OUT Creating build for app with guid 979f7403-b13c-4e85-936b-744064b691bc
2018-05-28T10:19:13.14+0200 [API/5] OUT Updated app with guid 979f7403-b13c-4e85-936b-744064b691bc ({"state"=>"STARTED"})
2018-05-28T10:19:13.36+0200 [STG/0] OUT Downloading liberty-for-java_v3_20-20180413-1252...
2018-05-28T10:19:13.36+0200 [STG/0] OUT Downloading dotnet-core...
2018-05-28T10:19:13.36+0200 [STG/0] OUT Downloading sdk-for-nodejs...
2018-05-28T10:19:13.36+0200 [STG/0] OUT Downloading java_buildpack...
2018-05-28T10:19:13.36+0200 [STG/0] OUT Downloading xpages_buildpack...
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloaded sdk-for-nodejs
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloading liberty-for-java...
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloaded java_buildpack
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloading ruby_buildpack...
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloaded dotnet-core
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloaded xpages_buildpack
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloading nodejs_buildpack...
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloading swift_buildpack...
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloaded liberty-for-java_v3_20-20180413-1252
2018-05-28T10:19:13.41+0200 [STG/0] OUT Downloading python_buildpack...
2018-05-28T10:19:13.44+0200 [STG/0] OUT Downloaded liberty-for-java
2018-05-28T10:19:13.44+0200 [STG/0] OUT Downloading php_buildpack...
2018-05-28T10:19:13.44+0200 [STG/0] OUT Downloaded swift_buildpack
2018-05-28T10:19:13.44+0200 [STG/0] OUT Downloading go_buildpack...
2018-05-28T10:19:13.44+0200 [STG/0] OUT Downloaded python_buildpack
2018-05-28T10:19:13.44+0200 [STG/0] OUT Downloading xpages_buildpack_v1_2_1-20160913-103...
2018-05-28T10:19:13.44+0200 [STG/0] OUT Downloaded ruby_buildpack
2018-05-28T10:19:13.44+0200 [STG/0] OUT Downloading swift_buildpack_v2_0_11-20180402-2018...
2018-05-28T10:19:13.45+0200 [STG/0] OUT Downloaded nodejs_buildpack
2018-05-28T10:19:13.45+0200 [STG/0] OUT Downloading staticfile_buildpack...
2018-05-28T10:19:13.47+0200 [STG/0] OUT Downloaded go_buildpack
2018-05-28T10:19:13.47+0200 [STG/0] OUT Downloading dotnet-core_v1_0_22-20170724-0813...
2018-05-28T10:19:13.47+0200 [STG/0] OUT Downloaded xpages_buildpack_v1_2_1-20160913-103
2018-05-28T10:19:13.47+0200 [STG/0] OUT Downloading binary_buildpack...
2018-05-28T10:19:13.47+0200 [STG/0] OUT Downloaded staticfile_buildpack
2018-05-28T10:19:13.47+0200 [STG/0] OUT Downloading sdk-for-nodejs_v3_20-20180403-1426...
2018-05-28T10:19:13.47+0200 [STG/0] OUT Downloaded swift_buildpack_v2_0_11-20180402-2018
2018-05-28T10:19:13.48+0200 [STG/0] OUT Downloaded php_buildpack
2018-05-28T10:19:13.50+0200 [STG/0] OUT Downloaded sdk-for-nodejs_v3_20-20180403-1426
2018-05-28T10:19:13.50+0200 [STG/0] OUT Downloaded binary_buildpack
2018-05-28T10:19:13.50+0200 [STG/0] OUT Downloaded dotnet-core_v1_0_22-20170724-0813
2018-05-28T10:19:13.50+0200 [STG/0] OUT Creating container
2018-05-28T10:19:13.92+0200 [STG/0] OUT Successfully created container
2018-05-28T10:19:13.92+0200 [STG/0] OUT Downloading app package...
2018-05-28T10:19:14.06+0200 [STG/0] OUT Downloaded app package (680.6K)
2018-05-28T10:19:14.06+0200 [STG/0] OUT Downloading build artifacts cache...
2018-05-28T10:19:15.66+0200 [STG/0] OUT Downloaded build artifacts cache (12.3M)
2018-05-28T10:19:15.66+0200 [STG/0] OUT Staging...
2018-05-28T10:19:18.58+0200 [STG/0] OUT -------> Buildpack version 1.6.46
2018-05-28T10:19:19.11+0200 [STG/0] OUT        Downloaded [https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-1.15.3-1bda8458.tgz]
2018-05-28T10:19:19.26+0200 [STG/0] OUT -----> Supplying Ruby/Rack
2018-05-28T10:19:19.26+0200 [STG/0] OUT        WARNING: Windows line endings detected in Gemfile. Your app may fail to stage. Please use UNIX line endings.
2018-05-28T10:19:19.73+0200 [STG/0] OUT  !
2018-05-28T10:19:19.73+0200 [STG/0] OUT  !     string contains null byte
2018-05-28T10:19:19.73+0200 [STG/0] OUT  !
2018-05-28T10:19:19.73+0200 [STG/0] ERR /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/base.rb:158:in ``': string contains null byte (ArgumentError)
2018-05-28T10:19:19.73+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/base.rb:158:in `log_internal'
2018-05-28T10:19:19.73+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/base.rb:128:in `rescue in log'
2018-05-28T10:19:19.73+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/base.rb:121:in `log'
2018-05-28T10:19:19.73+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/bin/supply:42:in `block in <main>'
2018-05-28T10:19:19.73+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/instrument.rb:35:in `block in trace'
2018-05-28T10:19:19.73+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
2018-05-28T10:19:19.73+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
2018-05-28T10:19:19.73+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/instrument.rb:17:in `block in instrument'
2018-05-28T10:19:19.74+0200 [STG/0] ERR 	from /usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
2018-05-28T10:19:19.74+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/instrument.rb:16:in `instrument'
2018-05-28T10:19:19.74+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/lib/language_pack/instrument.rb:35:in `trace'
2018-05-28T10:19:19.74+0200 [STG/0] ERR 	from /tmp/buildpacks/184d8e5a70d4971d932f0f92f7881ba6/bin/supply:39:in `<main>'
2018-05-28T10:19:19.74+0200 [STG/0] ERR Failed to compile droplet: Failed to run all supply scripts: exit status 1
2018-05-28T10:19:19.76+0200 [STG/0] OUT Exit status 223
2018-05-28T10:19:19.76+0200 [STG/0] ERR Staging failed: STG: Exited with status 223
2018-05-28T10:19:19.76+0200 [STG/0] OUT Stopping instance c21f9ce3-6922-4380-9ece-92487bc6941a
2018-05-28T10:19:19.76+0200 [STG/0] OUT Destroying container
2018-05-28T10:19:20.24+0200 [STG/0] OUT Successfully destroyed container
```

**Comment by sclevine** [comment]
Hi @stoprocent,

The version of the buildpack you are using is no longer supported and likely provides outdated and insecure dependencies. Can you upgrade to 1.7.18? Also, the warning seems to indicate that the Gemfile contains Windows line endings. Can you re-push the app with Unix line endings only?

**Comment by stoprocent** [comment]
Hi 

Issue is now fixed. It was a mix of outdated tool and small typo.

Thanks 

M
