### ISSUE TITLE
msfdb init 

### ISSUE THREAD

**Issue by sumanthgoud924** [cloudfoundry/ruby-buildpack#151]
unable to run msfdb init 
after complete update and upgrade 

root@kali:~# msfdb
Traceback (most recent call last):
        2: from /usr/local/bin/msfdb:10:in `<main>'
        1: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rex/socket (LoadError)
root@kali:~# msfdb init
Traceback (most recent call last):
        2: from /usr/local/bin/msfdb:10:in `<main>'
        1: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rex/socket (LoadError)

**Comment by kvedurmu** [comment]
Hi. It's likely that the core C libraries needed to use `msfdb` in Cloud Foundry are not installed by default on the [CFlinuxfs3 stack](https://github.com/cloudfoundry/cflinuxfs3/blob/main/receipt.cflinuxfs3.x86_64). 

What you can do here is determine the C libraries that are needed ([this seems promising](https://github.com/cloudfoundry/cflinuxfs3/blob/main/receipt.cflinuxfs3.x86_64)), and use the [Apt Buildpack](https://github.com/cloudfoundry/apt-buildpack) along with the Ruby Buildpack to push your app.

**Comment by ForestEckhardt** [comment]
Closing due to inactivity. Please feel free to reopen if you have an update or more to discuss.
