### ISSUE TITLE
Ruby app fails to start using Rails 5.2 without sprockets

### ISSUE THREAD

**Issue by thitch97** [cloudfoundry/ruby-buildpack#241]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.lavenderblue.cf-app.com",
   "token_endpoint": "https://uaa.lavenderblue.cf-app.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.lavenderblue.cf-app.com:2222",
   "app_ssh_host_key_fingerprint": "tmO60zEcXaDhijyUpgAVraY5DrTRaVTTj0D6Bu6iZbc",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.lavenderblue.cf-app.com:443",
   "api_version": "2.164.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.lavenderblue.cf-app.com/routing",
   "user": "e6faf00f-ccb3-42b9-9cad-ee82a36679fa"
}
cf version 6.53.0+8e2b70a4a.2020-10-01
```
What version of the buildpack you are using?
1.8.37

If you were attempting to accomplish a task, what was it you were attempting to do?
Build a Rails 5.2 application without using webpack/yarn instead of sprockets

What did you expect to happen?
App should start successfully

What was the actual behavior?
App is built successfully but fails to start, with the following output:
```
   2021-05-03T19:04:12.01+0000 [STG/0] OUT Uploading complete
   2021-05-03T19:04:12.19+0000 [STG/0] OUT Cell 495f37d1-095c-47a8-a1c8-c80b62d4bafe stopping instance ad85a131-cf2a-43e4-8c54-00226fa891c3
   2021-05-03T19:04:12.19+0000 [STG/0] OUT Cell 495f37d1-095c-47a8-a1c8-c80b62d4bafe destroying container for instance ad85a131-cf2a-43e4-8c54-00226fa891c3
   2021-05-03T19:04:12.42+0000 [CELL/0] OUT Cell 495f37d1-095c-47a8-a1c8-c80b62d4bafe creating container for instance c802e7cc-e53f-42c6-7e05-3aef
   2021-05-03T19:04:13.12+0000 [CELL/0] OUT Cell 495f37d1-095c-47a8-a1c8-c80b62d4bafe successfully created container for instance c802e7cc-e53f-42c6-7e05-3aef
   2021-05-03T19:04:13.29+0000 [CELL/0] OUT Downloading droplet...
   2021-05-03T19:04:15.41+0000 [STG/0] OUT Cell 495f37d1-095c-47a8-a1c8-c80b62d4bafe successfully destroyed container for instance ad85a131-cf2a-43e4-8c54-00226fa891c3
   2021-05-03T19:04:19.18+0000 [CELL/0] OUT Downloaded droplet (84.4M)
   2021-05-03T19:04:19.18+0000 [CELL/0] OUT Starting health monitoring of container
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:433:in `initialize': Disk quota exceeded @ rb_sysopen - /home/vcap/app/tmp/pids/server.pid (Errno::EDQUOT)
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:433:in `open'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:433:in `write_pid'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:317:in `start'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:53:in `start'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:147:in `block in perform'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `tap'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `perform'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<main>'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
   2021-05-03T19:04:24.39+0000 [APP/PROC/WEB/0] ERR     from bin/rails:9:in `<main>'
   2021-05-03T19:04:24.42+0000 [APP/PROC/WEB/0] OUT => Booting Puma
   2021-05-03T19:04:24.42+0000 [APP/PROC/WEB/0] OUT => Rails 5.2.5 application starting in production
   2021-05-03T19:04:24.42+0000 [APP/PROC/WEB/0] OUT => Run `rails server -h` for more startup options
   2021-05-03T19:04:24.42+0000 [APP/PROC/WEB/0] OUT Exiting
   2021-05-03T19:04:24.43+0000 [APP/PROC/WEB/0] OUT Exit status 1
```

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by menehune23** [comment]
Hey @thitch97, is this still important to look into?

**Comment by menehune23** [comment]
Closing as stale. Feel free to reopen if necessary @thitch97
