### ISSUE TITLE
can't push an app that relies on jdbc jars being on the classpath

### ISSUE THREAD

**Issue by mikfreedman** [cloudfoundry/ruby-buildpack#30]
When using v1.2.1 of the ruby buildpack we seem to have problems loading a jar during staging that we didn't have on 1.2.0!

*This is from a broken 1.2.1 deployment*
```bash
Restaging app app-name in org org-name / space sms...
-----> Downloaded app package (91M)
-----> Downloaded app buildpack cache (65M)
-------> Buildpack version 1.2.1
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-1.9.3-jruby-1.7.11
-----> Installing JVM: openjdk1.8-latest
Picked up JAVA_TOOL_OPTIONS: -Xmx768m -Djava.rmi.server.useCodebaseOnly=true
-----> Installing dependencies using 1.7.12
```

resulting in the following error during staging

```bash
RR /home/vcap/app/vendor/bundle/jruby/1.9/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb:38:in `(root)': ERROR: ActiveRecord oracle_enhanced adapter could not load Oracle JDBC driver. Please install Oracle JDBC library. (LoadError)
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyKernel.java:1085:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_connection.rb:1:in `(root)'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyKernel.java:1085:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_connection.rb:116:in `(root)'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyKernel.java:1085:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1:in `(root)'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyKernel.java:1085:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:36:in `(root)'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyArray.java:1613:in `each'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/cache/pam_client-cf9763696377/lib/pam_client.rb:1:in `(root)'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyArray.java:1613:in `each'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/cache/pam_client-cf9763696377/lib/pam_client.rb:2:in `(root)'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/bundler-1.7.12/lib/bundler/runtime.rb:1:in `(root)'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyKernel.java:1085:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyKernel.java:1893:in `tap'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/jruby/1.9/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from org/jruby/RubyKernel.java:1085:in `require'
2015-02-17T12:02:57.80-0500 [App/0]      ERR 	from script/rails:6:in `(root)'
2015-02-17T12:02:57.86-0500 [App/0]      OUT
2015-02-17T12:02:57.93-0500 [DEA/12]     ERR Instance (index 0) failed to start accepting connections
```

*This is from a working 1.2.0 deployment*
```
2015-02-17T11:59:21.78-0500 [STG/28]     OUT -----> Downloaded app package (92M)
2015-02-17T11:59:23.45-0500 [STG/28]     OUT -----> Downloaded app buildpack cache (65M)
2015-02-17T11:59:24.31-0500 [STG/0]      ERR Cloning into '/tmp/buildpacks/ruby-buildpack'...
2015-02-17T11:59:25.21-0500 [STG/0]      ERR Note: checking out '5e653b363f9848eb75c91a25e939f70a6e9fd046'.
2015-02-17T11:59:25.21-0500 [STG/0]      ERR You are in 'detached HEAD' state. You can look around, make experimental
2015-02-17T11:59:25.21-0500 [STG/0]      ERR changes and commit them, and you can discard any commits you make in this
2015-02-17T11:59:25.21-0500 [STG/0]      ERR state without impacting any branches by performing another checkout.
2015-02-17T11:59:25.21-0500 [STG/0]      ERR If you want to create a new branch to retain commits you create, you may
2015-02-17T11:59:25.21-0500 [STG/0]      ERR do so (now or later) by using -b with the checkout command again. Example:
2015-02-17T11:59:25.21-0500 [STG/0]      ERR   git checkout -b new_branch_name
2015-02-17T11:59:25.41-0500 [STG/0]      OUT Submodule 'compile-extensions' (https://github.com/cf-buildpacks/compile-extensions) registered for path 'compile-extensions'
2015-02-17T11:59:25.46-0500 [STG/0]      ERR Cloning into 'compile-extensions'...
2015-02-17T11:59:25.74-0500 [STG/0]      OUT Submodule path 'compile-extensions': checked out '6f91ed772234bfa0433f467d41e86c8e712466b6'
2015-02-17T11:59:25.89-0500 [STG/0]      OUT -------> Buildpack version 1.2.0
2015-02-17T11:59:26.78-0500 [STG/0]      OUT -----> Compiling Ruby/Rails
2015-02-17T11:59:28.48-0500 [STG/0]      OUT -----> Using Ruby version: ruby-1.9.3-jruby-1.7.11
2015-02-17T11:59:28.48-0500 [STG/0]      OUT -----> Installing JVM: openjdk7-latest
2015-02-17T11:59:30.75-0500 [STG/0]      ERR Picked up JAVA_TOOL_OPTIONS: -Djava.rmi.server.useCodebaseOnly=true
2015-02-17T11:59:32.99-0500 [STG/0]      OUT -----> Installing dependencies using 1.6.3
```

it would seem that the most salient differences are:

* Environment variables:

1.2.1
```
JAVA_TOOL_OPTIONS: -Xmx768m -Djava.rmi.server.useCodebaseOnly=true
```

1.2.0
```
JAVA_TOOL_OPTIONS: -Djava.rmi.server.useCodebaseOnly=true
```

* Java 8 vs Java 7
* Bundler 1.7.12 vs Bundler 1.6.3

FWIW it seems that the `/lib/` directory is automatically included in the `CLASSPATH` somehow during bundling for the 1.2.0 version of the buildpack.

bash
```
$ ls -a lib/*.jar
lib/log4j-1.2.17.jar lib/ojdbc6.jar       lib/ojdbc7.jar
```

**Comment by jchesterpivotal** [comment]
## Workaround

```bash
echo 'java.runtime.version=1.7' > system.properties
```

## Explanation

Ruby buildpack 1.2.1 pulled in numerous upstream changes from Heroku.

A key change, which we did not notice at the time, is that the buildpack now selects [JDK 1.8 as the default JRuby JDK](https://github.com/cloudfoundry/ruby-buildpack/commit/e20aac0b0632f0835c6dec0a1046bab85a04a57f).

The oracle_enhanced gem [at version 1.4.3 doesn't recognise JDK 1.8](https://github.com/rsim/oracle-enhanced/blob/bdbdbddb70755be896060d33db31bfbe4e92a1fa/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb#L15).
When it sees this JDK version, it refuses to identify any `ojdbc` jar files. Loading fails because no file is identified.

Upgrading to version 1.5.5 of oracle_enhanced [adds support for 1.8](https://github.com/rsim/oracle-enhanced/blob/v1.5.5/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb#L12).

## Why the workaround works

The buildpack looks in the `system.properties` file for a JDK version. If you set it to 1.7, the older gem works.
