### ISSUE TITLE
Ruby buildpack failed to analyze Gemfile with ruby syntax

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry/ruby-buildpack#60]
What version of Cloud Foundry are you using?
version: 220

What version of the buildpack you are using?
v1.6.19

If you were attempting to accomplish a task, what was it you were attempting to do?

```
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

$ bundle -v
Bundler version 1.11.2

$ gem -v
2.4.8

$ cat manifest.yml
---
applications:
  - name: hello-ruby
    buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.6.19

$ cat Gemfile
source 'https://rubygems.org'

gem "mime-types", (RUBY_VERSION >= "2.0" ? "~> 3.0" : "~> 2.99") # Breaks building, get from redmine 3.2.3
gem 'sinatra'
gem 'puma'

$ bundle install
...

$ cf push --random-route
Using manifest file <...>/hello-ruby/manifest.yml

Updating app hello-ruby in <...>...
OK

Creating route <...>...
OK

Binding <...>...
OK

Uploading hello-ruby...
Uploading app files from: <...>/hello-ruby
Uploading 2.9M, 773 files
Done uploading
OK

Stopping app hello-ruby in <...>...
OK

Starting app hello-ruby in <...>...
-----> Downloaded app package (2.4M)
-----> Downloaded app buildpack cache (2.2M)
Cloning into '/tmp/buildpacks/ruby-buildpack'...
Note: checking out '721f78f9af3da2891c6ca27cafe8c3f8051cb5fb'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
do so (now or later) by using -b with the checkout command again. Example:
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
  git checkout -b new_branch_name
Submodule 'compile-extensions' (https://github.com/cloudfoundry/compile-extensions) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '4a0e48afc46c1d467b7c75a8ae5e6f3a044d3d64'
-------> Buildpack version 1.6.19
       Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/concourse-binaries/bundler/bundler-1.12.5.tgz]
-----> Compiling Ruby/Rack
sh: 1: Syntax error: EOF in backquote substitution
 !
 !     undefined method `>=' for nil:NilClass
 !
./Gemfile:3:in `ruby_requirement': undefined method `>=' for nil:NilClass (NoMethodError)
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby_semver_version.rb:32:in `instance_eval'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby_semver_version.rb:32:in `ruby_requirement'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby_semver_version.rb:7:in `initialize'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby_version.rb:126:in `new'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby_version.rb:126:in `update_version'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby_version.rb:38:in `initialize'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby.rb:187:in `new'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby.rb:187:in `block in ruby_version'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/base.rb:48:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/base.rb:44:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby.rb:180:in `ruby_version'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby.rb:331:in `block in install_ruby'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/base.rb:48:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/base.rb:44:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby.rb:330:in `install_ruby'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby.rb:93:in `block in compile'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/base.rb:48:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/base.rb:44:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/ruby.rb:88:in `compile'
	from /tmp/buildpacks/ruby-buildpack/bin/compile:23:in `block (2 levels) in <main>'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/base.rb:129:in `log'
	from /tmp/buildpacks/ruby-buildpack/bin/compile:22:in `block in <main>'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:35:in `call'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:35:in `block in trace'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/buildpacks/ruby-buildpack/lib/language_pack/instrument.rb:35:in `trace'
	from /tmp/buildpacks/ruby-buildpack/bin/compile:18:in `<main>'
Staging failed: Buildpack compilation step failed

FAILED
Error restarting application: BuildpackCompileFailed

TIP: use 'cf logs hello-ruby --recent' for more information

```

What did you expect to happen?
I tried to push redmine 3.2.3 to the cloudfoundry with latest buildpack (v1.6.19), but it fails. Seems like during ruby-buildpack building ruby applications, there is a preprocess on Gemfile and it breaks on non-trivial Gemfile.

The ruby-buildpack v1.6.17 works and the v1.6.18/v1.6.19 breaks.

Also syntax in Gemfile such as 

```
if Gem::Version.new(Bundler::VERSION) < Gem::Version.new('1.5.0')
  abort "Redmine requires Bundler 1.5.0 or higher (you're using #{Bundler::VERSION}).\nPlease update with 'gem update bundler'."
end
```
also fails. This is also from redmine Gemfile.

What was the actual behavior?

Described above

Please confirm where necessary:
* [Y] I have included a log output 
* [Y] My log includes an error message 
* [Y] I have included steps for reproduction

**Comment by flavorjones** [comment]
@liuweichu Have you tried using `::Gem` instead of plain-old `Gem`?

If not, please do and let us know how you get on.

**Comment by flavorjones** [comment]
Actually, this log message:

```
sh: 1: Syntax error: EOF in backquote substitution
```

is not good. Something else is going on. @RochesterinNYC any ideas?

**Comment by cf-buildpacks-eng** [comment]
@liuweichu Thanks, we have added both of your examples to our test suite. We are now leveraging Bundler's DSL evaluator directly, and so the buildpack will correctly handle any Gemfile which is valid for Bundler.

Could you please push using the develop branch (eg. `cf push test -b https://github.com/cloudfoundry/ruby-buildpack.git#develop`) and tell us either way. If it works we will close this issue.

**Comment by liuweichu** [comment]
@cf-buildpacks-eng 
Tested on develop branch, it works!
Thank you for the quick respond.

Close this issue.

**Comment by liuweichu** [comment]
@flavorjones Hi, I'm not sure what is `::Gem`. Could you please give me some more explanation?

**Comment by allomov** [comment]
@liuweichu two double-colon tells ruby to start search for constant in global scope. You can find some details [here](http://stackoverflow.com/questions/3009477/what-is-rubys-double-colon).

I already created a PR to solve this issue https://github.com/cloudfoundry/ruby-buildpack/pull/57, but it was not fully accepted. This particular problem is caused, because `const_missing` in `LanguagePack::RubySemverVersion` doesn't have return anything and ruby returns `nil` as a result of such functions ([link to code](https://github.com/cloudfoundry/ruby-buildpack/blob/6f0f13ffbd6e15717afcbf108250e5051b9f179c/lib/language_pack/ruby_semver_version.rb#L51)). This `nil` and caused this `undefined method ... for nil:NilClass` in your case.

I think, that `::` will help in your case.

**Comment by allomov** [comment]
@liuweichu looks like [this commit](https://github.com/cloudfoundry/ruby-buildpack/commit/df1aa3c24351ca1686195069063f4f1d22d8b1cc) should fix this issue in following ruby-buildpack version. 

You can also use `develop` branch to try this fixes right now, just push your app in the following way:
```
cf push <app-name> -b https://github.com/cloudfoundry/ruby-buildpack#develop
```

**Comment by liuweichu** [comment]
@allomov Thanks for telling me a new ruby trick 😃 
I tested the develop against redmine's Gemfile, and it works perfectly.
