### ISSUE TITLE
Cannot compile ruby-oci8 gem

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry/ruby-buildpack#69]
What version of Cloud Foundry are you using?
v230

What version of the buildpack you are using?
1.6.28

If you were attempting to accomplish a task, what was it you were attempting to do?
Push an ruby app which uses "ruby-oci8" gem

What did you expect to happen?
Since the installation of `ruby-oci8` requires `LD_LIBRARY_PATH` and `PATH` pointing to Oracle Instance Client diretory.
I expect there is a easy way to set **user provided** environment variables **during staging phase** in manifest, so that bundle can detect and use them.

What was the actual behavior?

```
$ cat Gemfile
source 'https://rubygems.org'
gem 'sinatra'
gem 'puma'
gem 'ruby-oci8'

# Oracle client, Need to include this to LD_LIBRARY_PATH and PATH during staging
# Download from http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html
# Require Basic.zip and SDK.zip
$ ls instantclient_12_1/
adrci         genezi                 libclntsh.so       libipc1.so  libnnz12.so  libocci.so.12.1  libocijdbc12.so  liboramysql12.so  ojdbc7.jar  uidrvci
BASIC_README  libclntshcore.so.12.1  libclntsh.so.12.1  libmql1.so  libocci.so   libociei.so      libons.so        ojdbc6.jar        sdk         xstreams.jar

$ bundle package --all
Using puma 3.6.0
Using rack 1.6.5
Using ruby-oci8 2.2.2
Using tilt 2.0.5
Using bundler 1.13.6
Using rack-protection 1.5.3
Using sinatra 1.4.7
Updating files in vendor/cache
Bundle complete! 3 Gemfile dependencies, 7 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Updating files in vendor/cache



$ cf push
......
-----> Downloaded app package (79M)
-----> Downloaded app buildpack cache (2.0M)
Cloning into '/tmp/buildpacks/ruby-buildpack'...
Submodule 'compile-extensions' (https://github.com/rakutentech/compile-extensions) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '7985e1c153d80ca9563a289b8026f0acb45e03d2'
-------> Buildpack version 1.6.28
       Downloaded [https://buildpacks.cloudfoundry.org/concourse-binaries/bundler/bundler-1.13.6.tgz]
-----> Compiling Ruby/Rack
       Downloaded [https://buildpacks.cloudfoundry.org/concourse-binaries/ruby/ruby-2.3.1-linux-x64.tgz]
-----> Using Ruby version: ruby-2.3.1
###### WARNING:
       You have the `.bundle/config` file checked into your repository
       It contains local state like the location of the installed bundle
       as well as configured git local gems, and other settings that should
       not be shared between multiple checkouts of a single repo. Please
       remove the `.bundle/` folder from your repo and add it to your `.gitignore` file.
-----> Installing dependencies using bundler 1.13.6
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Using puma 3.6.0
       Using rack 1.6.5
       Installing ruby-oci8 2.2.2 with native extensions
       Using tilt 2.0.5
       Using bundler 1.13.6
       Using rack-protection 1.5.3
       Using sinatra 1.4.7
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       current directory:
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8
       /tmp/staged/app/vendor/ruby-2.3.1/bin/ruby -r ./siteconf20161111-295-r4jh0h.rb
       extconf.rb
       checking for load library path...
       LD_LIBRARY_PATH...
       checking /home/vcap/app/instantclient_12_1... no
       checking ld.so.conf... no
       checking for cc... ok
       checking for gcc... yes
       checking for LP64... yes
       checking for sys/types.h... yes
       checking for ruby header... ok
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/tmp/staged/app/vendor/ruby-2.3.1/bin/$(RUBY_BASE_NAME)
       --with-instant-client
       --without-instant-client
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:963:in
       `get_home': RuntimeError (RuntimeError)
       from
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:779:in
       `initialize'
       from
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:320:in
       `new'
       from
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:320:in
       `get'
       Error Message:
       from extconf.rb:22:in `<main>'
       ---------------------------------------------------
       Set the environment variable ORACLE_HOME if Oracle Full Client.
       Append the path of Oracle client libraries to LD_LIBRARY_PATH if Oracle
       Instant Client.
       Backtrace:
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:963:in
       `get_home'
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:779:in
       `initialize'
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:320:in
       `new'
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:320:in
       `get'
       extconf.rb:22:in `<main>'
       ---------------------------------------------------
       See:
       *
       http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-full-client.md
       for Oracle full client
       *
       http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-instant-client.md
       for Oracle instant client
       * http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-on-osx.md for
       OS X
       *
       http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/report-installation-issue.md
       to report an issue.
       To see why this extension failed to compile, please check the mkmf.log which can
       be found here:
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/ruby-oci8-2.2.2/mkmf.log
       extconf failed, exit code 1
       Gem files will remain installed in
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2 for inspection.
       Results logged to
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/ruby-oci8-2.2.2/gem_make.out
       An error occurred while installing ruby-oci8 (2.2.2), and Bundler cannot
       continue.
       Make sure that `gem install ruby-oci8 -v '2.2.2'` succeeds before bundling.
       Bundler Output: Using puma 3.6.0
       Using rack 1.6.5
       Installing ruby-oci8 2.2.2 with native extensions
       Using tilt 2.0.5
       Using bundler 1.13.6
       Using rack-protection 1.5.3
       Using sinatra 1.4.7
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       current directory:
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8
       /tmp/staged/app/vendor/ruby-2.3.1/bin/ruby -r ./siteconf20161111-295-r4jh0h.rb
       extconf.rb
       checking for load library path...
       LD_LIBRARY_PATH...
       checking /home/vcap/app/instantclient_12_1... no
       checking ld.so.conf... no
       checking for cc... ok
       checking for gcc... yes
       checking for LP64... yes
       checking for sys/types.h... yes
       checking for ruby header... ok
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/tmp/staged/app/vendor/ruby-2.3.1/bin/$(RUBY_BASE_NAME)
       --with-instant-client
       --without-instant-client
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:963:in
       `get_home': RuntimeError (RuntimeError)
       from
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:779:in
       `initialize'
       from
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:320:in
       `new'
       from
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:320:in
       `get'
       from extconf.rb:22:in `<main>'
       ---------------------------------------------------
       Error Message:
       Set the environment variable ORACLE_HOME if Oracle Full Client.
       Append the path of Oracle client libraries to LD_LIBRARY_PATH if Oracle
       Instant Client.
       Backtrace:
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:963:in
       `get_home'
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:779:in
       `initialize'
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:320:in
       `new'
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2/ext/oci8/oraconf.rb:320:in
       `get'
       extconf.rb:22:in `<main>'
       ---------------------------------------------------
       See:
       *
       http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-full-client.md
       for Oracle full client
       *
       http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-instant-client.md
       for Oracle instant client
       * http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-on-osx.md for
       OS X
       *
       http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/report-installation-issue.md
       to report an issue.
       To see why this extension failed to compile, please check the mkmf.log which can
       be found here:
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/ruby-oci8-2.2.2/mkmf.log
       extconf failed, exit code 1
       Gem files will remain installed in
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/gems/ruby-oci8-2.2.2 for inspection.
       Results logged to
       /tmp/staged/app/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/ruby-oci8-2.2.2/gem_make.out
       An error occurred while installing ruby-oci8 (2.2.2), and Bundler cannot
       continue.
       Make sure that `gem install ruby-oci8 -v '2.2.2'` succeeds before bundling.
 !
 !     Failed to install gems via Bundler.
 !
Staging failed: Buildpack compilation step failed
```

Please confirm where necessary:
* [yes] I have included a log output 
* [yes] My log includes an error message 
* [yes] I have included steps for reproduction

**Comment by giner** [comment]
As a test I tried to put oracle libs to libs_native and apply the following change to the buildpack and it worked for me:
```
--- a/bin/compile
+++ b/bin/compile
@@ -6,6 +6,8 @@ $stdout.sync = true
 cache_dir = ARGV[1]
 compile_extensions_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'compile-extensions'))
 
+ENV["LD_LIBRARY_PATH"] = "#{ARGV[0]}/libs_native"
+
 exit(44) unless system("#{compile_extensions_dir}/bin/check_stack_support")
 
 $:.unshift File.expand_path("../../lib", __FILE__)
```

**Comment by sclevine** [comment]
Environment variables specified in an application's `manifest.yml` file are exposed during staging (at least in CF v239, not sure about v230). You may be able to set `LD_LIBRARY_PATH` there.

**Comment by CAFxX** [comment]
@sclevine is this behavior documented somewhere? I checked https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#env-block but couldn't find any mention of this...

**Comment by giner** [comment]
Thank you @sclevine. I can confirm, specifying variable in manifest helps (release v230).
At the same time it seems to be not mentioned anywhere in documentation as @CAFxX already said.

**Comment by RochesterinNYC** [comment]
Thanks @CAFxX and @giner for bringing this to our attention. Submitted a PR to the docs to update it with a note about the manifest env vars being in the staging container environment as well: cloudfoundry/docs-dev-guide#137

**Comment by pcsgithubid** [comment]
I have added the ```  LD_LIBRARY_PATH: /home/vcap/app/ld_library_path``` to manifest file, but still the ruby oci8 gem fails. Please assist me.

**Comment by pcsgithubid** [comment]
i have added all libs to ```app/ld_library_path``` in the code base.

**Comment by n-gottam** [comment]
@pcsgithubid Did that work for you? I am looking for the same. Please let me know. Thanks.

**Comment by n-gottam** [comment]
@liuweichu Could you please share what you ended up doing to resolve this?

**Comment by pcsgithubid** [comment]
@liuweichu Still working on this issue

**Comment by dgodd** [comment]
@pcsgithubid @n-gottam  If you could open a new issue and provide a sample app which fails, we can look into this for you

**Comment by giner** [comment]
@pcsgithubid, the following should work:
`LD_LIBRARY_PATH: ld_library_path`
or
`LD_LIBRARY_PATH: mylib:/tmp/app/mylib`
