### ISSUE TITLE
rails 7.1 compatibility

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/ruby-buildpack#865]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
api_version":"2.214.0"
cf version 8.7.4+db5d612.2023-10-20
```
What version of the buildpack you are using?

ruby_buildpack-cached-cflinuxfs4-v1.10.5.zip

If you were attempting to accomplish a task, what was it you were attempting to do?

Create a new rails 7.1 app via `rails new cf-rails-mysql --database mysql --skip-action-cable` and then `cf push my-rails-app`

What did you expect to happen?

CF to start and run the app.

What was the actual behavior?

The app fails in staging with an error about `rake secret` not being a valid task. Looks like this went away in rails 7, and possibly is now `rails secret`?

```
   Installing rails 7.1.1
   Bundle complete! 14 Gemfile dependencies, 69 gems now installed.
   Gems in the groups 'development' and 'test' were not installed.
   Bundled gems are installed into `/tmp/contents3191792260/deps/0/vendor_bundle`
   -----> Regenerating bundler binstubs...
   Cleaning up the bundler cache.
   -----> Creating runtime environment
   rake aborted!
   Don't know how to build task 'secret' (See the list of available tasks with `rake --tasks`)
   /tmp/contents3191792260/deps/0/vendor_bundle/ruby/3.2.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:58:in `load'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:58:in `kernel_load'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:23:in `run'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/cli.rb:492:in `exec'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/cli.rb:34:in `dispatch'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/cli.rb:28:in `start'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
   /tmp/contents3191792260/deps/0/bundler/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
   /tmp/contents3191792260/deps/0/bin/bundle:108:in `load'
   /tmp/contents3191792260/deps/0/bin/bundle:108:in `<main>'
   (See full trace by running task with --trace)
   **ERROR** Unable to write profile.d: Failed to run 'rake secret': exit status 1
BuildpackCompileFailed - App staging failed in the buildpack compile phase
FAILED
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by Spimtav** [comment]
Bumping this issue.  i'm trying to upgrade my app to Rails 7.1 and am running into the exact same problem with the exact same output/reason.  Seems like we're stuck on Rails 7.0 until the ruby-buildpack is updated.

**Comment by sophiewigmore** [comment]
changes to support this were released in https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.10.13. thank you!
